# Generated by Django 2.2.3 on 2019-07-06 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_mynotes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MyNotes',
            new_name='MyNotess',
        ),
    ]
